# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecommendCreditCard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecommendCreditCard
pod 'Firebase/Database'
pod 'Kingfisher', '6.3.1'
pod 'lottie-ios', '3.2.3'

pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'

  target 'RecommendCreditCardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecommendCreditCardUITests' do
    # Pods for testing
  end

end
